> test() ? Testing TimescaleR ? The package "RPostgres" (>= 1.3.0) is required. ? Would you like to install it?
1: Yes
2: No

Selection: Yes

TimescaleR loaded successfully. Use init_connection() to set up a global database connection.
? | F W  S  OK | Context
? |          0 | config                                                                             Checking TimescaleR environment state:
 - Package environment (.TimescaleR): EXISTS
 - Global connection object: MISSING
 - Connection configuration: MISSING

Troubleshooting tips:
 1. Use library(TimescaleR) before making any function calls
 2. Always use TimescaleR::init_connection() first
 3. For namespace calls (TimescaleR::function), make sure all calls use the namespace
? |         44 | config
? | 1        0 | continuous_aggregates
----------------------------------------------------------------------------------------------------
Error (test-continuous_aggregates.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-continuous_aggregates.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | db_info
----------------------------------------------------------------------------------------------------
Error (test-db_info.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-db_info.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | monitor
----------------------------------------------------------------------------------------------------
Error (test-monitor.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-monitor.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | query
----------------------------------------------------------------------------------------------------
Error (test-query.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-query.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | system
----------------------------------------------------------------------------------------------------
Error (test-system.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-system.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | table_utils
----------------------------------------------------------------------------------------------------
Error (test-table_utils.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-table_utils.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | tables
----------------------------------------------------------------------------------------------------
Error (test-tables.R:5:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-tables.R:5:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | timescale
----------------------------------------------------------------------------------------------------
Error (test-timescale.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-timescale.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------
? | 1        0 | visualization
----------------------------------------------------------------------------------------------------
Error (test-visualization.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-visualization.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)
----------------------------------------------------------------------------------------------------

-- Results -----------------------------------------------------------------------------------------
Duration: 1.5 s

-- Failed tests ------------------------------------------------------------------------------------
Error (test-continuous_aggregates.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-continuous_aggregates.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

Error (test-db_info.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-db_info.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

Error (test-monitor.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-monitor.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

Error (test-query.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-query.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

Error (test-system.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-system.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

Error (test-table_utils.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-table_utils.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

Error (test-tables.R:5:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-tables.R:5:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

Error (test-timescale.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-timescale.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](Fixed Daypos stress library issues. cond)

Error (test-visualization.R:4:1): (code run outside of `test_that()`)
Error: package or namespace load failed for ‘RPostgres’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/RPostgres/libs/RPostgres.so':
  libpq.so.5: cannot open shared object file: No such file or directory
Backtrace:
    ?
 1. +-base::library(RPostgres) at test-visualization.R:4:1
 2.   +-base::tryCatch(...)
 3.     +-base (local) tryCatchList(expr, classes, parentenv, handlers)
 4.       +-base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5.         +-value[[3L]](cond)

[ FAIL 9 | WARN 0 | SKIP 0 | PASS 44 ]